require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserInfosController do

  include Devise::TestHelpers

  before :each do
    User.create!(:email => "test@test.com", :password => "1234567", :password_confirmation => "1234567").confirm!
    @user = User.find_by_email("test@test.com")
    sign_in :user,@user
  end

  describe "GET show" do
    it "assigns the requested user_info as @user_info" do
      user_info = UserInfo.create!()
      @user.user_info = user_info
      get :show
      assigns(:user_info).should eq(user_info)
    end
  end


end
